### ISSUE TITLE
Docs on setting up simple fully trusted cluster

### ISSUE THREAD

**Issue by swedneck** [ipfs/ipfs-cluster-website#118]
My specific use case is simply making sure my screenshots are always available, e.g. if i share a screenshot from my laptop while in an area with spotty connection, i want to make sure my desktop (with a good connection) has the image pinned.

**Comment by RubenKelevra** [comment]
As we discussed that in the chat, that are the details of your setup:

- You don't publish the cluster secret
- You want to trust all nodes (with write access) which have the cluster secret
- You want a one-liner (or close to that) to add additional cluster members which has to have write rights

**Comment by hsanjuan** [comment]
Is there anything you want to do that is not explained in the docs?
