### ISSUE TITLE
Time to review all content on this website

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster-website#2]
During the last weeks I have been moving all IPFS Cluster content to the website, writing and rewriting many things in detail (specially all around setup).

Now the website is ready to the point where we can make a collaborative effort to find issues:

* Things not documented enough
* Things too documented, or documented in the wrong place
* General organization
* Typos, bad syntax, bad grammar
* Design issues
* Etc.

The website is available at https://cluster.ipfs.io and every merge to master here automatically deploys a new version of it.

**Comment by lanzafame** [comment]
s/shortnesses/limitations
https://cluster.ipfs.io/documentation/overview/#current-shortnesses

**Comment by lanzafame** [comment]
[Overview](https://cluster.ipfs.io/documentation/overview) page doesn't have a link at the bottom to the next page in the Documentation ToC.

**Comment by lanzafame** [comment]
Configuration page: 
> Using different keys will prevent different peers from talking to each other.

Maybe this is fine but to me, it's the wrong way round from the perspective of someone setting up a cluster. To me it makes more sense to frame the statement as follows:

> Different peers must share the same secret key to be able to talk to each other.

I guess the difference being, the former is from the perspective of 'If you do this, it will break', whereas, the later is 'This is what you must do to make it work'.

**Comment by lanzafame** [comment]
@hsanjuan Just realised this probably isn't the most useful way to provide feedback. I will convert the above comments into separate issues.
