### ISSUE TITLE
Setup IPFS -cluster on Mac

### ISSUE THREAD

**Issue by sandeep1116** [ipfs/ipfs-cluster-website#27]
Hi ,

Do we have any dmg file to install IPFS-Cluster-Service on macbook.
Also as i am new to this can anyone help me to explain its usability . As far as   i understood with IPFS cluster service your IPFS content will pinned to your local storage server .
Please correct me i am wrong.

**Comment by akamarkman** [comment]
Howdy @sandeep1116, this is the issue section for the IPFS cluster website itself—not the code for IPFS cluster—so your questions might get some better/longer answers on the [IPFS cluster issues page](https://github.com/ipfs/ipfs-cluster/issues).

To answer your question though, there's currently no DMG install option for OSX. For most things IPFS related right now you'll need to use terminal, and I highly recommend this workshop series from Textile.photos (very up to date! recently posted!) as a primer for IPFS and usability, Carson explains the pinning process in workshop 1: https://www.youtube.com/watch?v=gOzAYiT1Z4U&list=PLC8CEtJ9shDznO1tpvGe--BVEWmCKY9_Z

**Comment by kishansagathiya** [comment]
> Also as i am new to this can anyone help me to explain its usability . As far as i understood with IPFS cluster service your IPFS content will pinned to your local storage server .

IPFS-Cluster does pinset orchestration. Say you have a bunch of IPFS nodes and you want to replicate some data across different nodes, say you want to make sure that x replication, you can do that with IPFS-Cluster. (There is more explanation on the website https://cluster.ipfs.io/)

I am going to close this, but if you still have doubts feel free to ask on #ipfs-cluster IRC, discuss.ipfs.io or open an issue on `ipfs/ipfs-cluster`
