### ISSUE TITLE
Make Cluster website work on mobile

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/ipfs-cluster-website#46]
'Nuf said.

**Comment by hsanjuan** [comment]
It's a static website. I can't be more responsive.

**Comment by meiqimichelle** [comment]
Maybe we are talking about different things @hsanjuan . A static website can absolutely be responsive. It is done via media queries in CSS.

**Comment by hsanjuan** [comment]
Can you explain the Problem? I don't understand

**Comment by meiqimichelle** [comment]
Right now, our website doesn't adapt to the user's screen size as it should. This leads to problems like this screenshot of our site on my mobile phone where much of the site is inaccessible:
<img src="https://user-images.githubusercontent.com/4827522/49828375-ef5b2280-fd48-11e8-8897-a829dac10f86.png" width="300" />

This issue is to remind me to do the work of making the Cluster site responsive, which involves adding media queries to the CSS and making design and code choices that help the layout flow as the user's screen size changes.

**Comment by hsanjuan** [comment]
ahh sorry. As I understood `responsive` it meant it's slow, or takes time to react or something.

**Comment by meiqimichelle** [comment]
Closed with #55 .
