### ISSUE TITLE
Documentation regarding environment variables used

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/ipfs-cluster-website#47]
We are using environment variables to modify config
At the moment it is not documented which env vars are available. It would be nice to have that along with what they are for. For this we can add a column for env vars in [such](https://cluster.ipfs.io/documentation/configuration/#ipfshttp) tables
https://github.com/ipfs/ipfs-cluster/pull/617#discussion_r242027931

I also wonder if it would be worth the time trying to automate some parts of this documentation.
For example, when I change some config field `proxy_listen_multiaddress` to `listen_multifield`, docs reflect that own its own and without one of us needing to manually change that.

**Comment by hsanjuan** [comment]
Using env vars is documented: https://cluster.ipfs.io/documentation/configuration/#using-environment-variables-to-overwrite-configuration-values

**Comment by hsanjuan** [comment]
The rate at which we change configuration variables is low enough that maintaining the automatic documentation generation would probably cost more time than maintaining the documentation directly, so I'm not convinced.

**Comment by kishansagathiya** [comment]
> Using env vars is documented:

I can close this then
