### ISSUE TITLE
download page missing in ipfs-cluster documentation

### ISSUE THREAD

**Issue by dannyob** [ipfs/ipfs-cluster-website#50]
I'm getting this error when I try and visit the download page.

```
ipfs resolve -r /ipns/cluster.ipfs.io/documentation/download: no link named "download" under Qmbxjqyik8BSBerKcWfnLkd3KNwJZfuzpHpWWf8iePy6yq
```

Thanks!

**Comment by hsanjuan** [comment]
Thanks for reporting. It's here now: https://cluster.ipfs.io/download/

@meiqimichelle  ^^^ can you see if we missed an alias or something? We should update the link in the documentation overview.
