### ISSUE TITLE
Guidelines for contributing link got broken

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-cluster-website#57]
https://cluster.ipfs.io/developer/contribute is linked from CONTRIBUTE.md and it stopped working. Probably missing an alias here.

**Comment by meiqimichelle** [comment]
I made one attempt to fix this, it does not seem to have worked. I will need to investigate further. My quick-fix was A+ "quick", D- "fix" , it turns out.

**Comment by hsanjuan** [comment]
Check if website is deploying at all

**Comment by hsanjuan** [comment]
I deployed the website manually and seems to work. Thanks!
