### ISSUE TITLE
Download documentation link broken

### ISSUE THREAD

**Issue by alien35** [ipfs/ipfs-cluster-website#63]
Doesn't work:
```https://cluster.ipfs.io/documentation/download```

Response:
```ipfs resolve -r /ipns/cluster.ipfs.io/documentation/download: no link named "download" under QmcfJkuLLvdMgh5FNfdiaG6XV4PFnkh833B322Jshyu3Vv```

**Comment by hsanjuan** [comment]
Where is this link?

cc @meiqimichelle
