### ISSUE TITLE
docs/configuration: raw json dump of default configuration visually difficult to decipher 

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster-website#7]
I think having the option name, default value and explanation comment on the one line is a bit much and considering that json doesn't support comments it isn't like a reader could use the json without having to edit it anyway (not that they would need to but it doesn't serve any real purpose being in json format in the docs).

**Comment by hsanjuan** [comment]
Right. I wouldn't want the users to use it, it's just meant to be a quick reference. Would you suggest having subsections for every component and writing down descriptions of the configuration options?

**Comment by lanzafame** [comment]
Yeah, subsections for each component with the descriptions would be easier to digest.
