### ISSUE TITLE
docs/configuration: what is the purpose of manually generating a private key and peer id

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster-website#8]
This section feels a bit odd, it is not obviously clear as to why someone would do this over leaving it to `ipfs-cluster-service init` to do this step. Also, it is not specified how you would go about using these values.

https://cluster.ipfs.io/documentation/configuration/#manually-generating-a-private-key-and-peer-id

**Comment by hsanjuan** [comment]
When you are automating a deployment, very probably you are just templating a single cluster configuration (ansible, puppet, chef..). That shows how to obtain id/private_keys values that you can pass to any template generator, without having to run `init` just to do it. It is also useful for ipfs.

It also serves to rotate keys without having to regenerate the configs.

**Comment by lanzafame** [comment]
Putting that information in the docs would be useful as context.
