### ISSUE TITLE
Do we need to add cache busting?

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/ipfs-cluster-website#81]
We shipped the website refactor in #55. I'm not sure where IPFS sites stand regarding cache busting. I'm thinking lots of people will see what looks like a half-broken Cluster site, depending on what browser they're using; their cache settings; and server settings on our end (and what about those who access our site via ipfs?).

@olizilla @alanshaw do you know anything about how we've dealt with this on other sites? I'd love for you to tell me I'm worrying too much. That is also an acceptable response.

**Comment by olizilla** [comment]
Always worth considering! But is fine! The gateway uses the resolved CID for the site root as the ETag header. Browsers who have seen the old cluster site will offer up the old CID on the request for the https://cluster.ipfs.io and the server knows that they need to get the new html. Same goes for the other resources, so they'll get crispy fresh `200` responses for all the things. Subsequent requests will get speedy `304 Not modifed` responses as the browser will now be sending up the current CID for the site./
