### ISSUE TITLE
What is IPFS Cluster

### ISSUE THREAD

**Issue by pkafei** [ipfs/ipfs-cluster-website#84]
Create a high level description that covers key concepts and vocabulary associated with IPFS Cluster. This would serve as a first entry point on https://cluster.ipfs.io/ to learn about Cluster.

**Comment by meiqimichelle** [comment]
We do need a 'what is Cluster'. The vocab will not likely be on the homepage. Is this issue for the vocab we need somewhere, or about redesigning the homepage? Those should be two separate issues.

**Comment by meiqimichelle** [comment]
Also, there is an existing homepage redesign issue at #56 .

**Comment by meiqimichelle** [comment]
The vocab part of this issue is now in #87 and the homepage redesign issue is in #56 . Closing.
