### ISSUE TITLE
Content Audit of IPFS Cluster Website

### ISSUE THREAD

**Issue by pkafei** [ipfs/ipfs-cluster-website#85]
Comprehensive survey of all of the pages that exist on https://cluster.ipfs.io/ Audit will prevent duplicating content, and assist in creating sitemap of future documentation.

**Comment by meiqimichelle** [comment]
@pkafei please link to the content audit, and make sure the link is open to the public to view. You can also assign this to yourself, and close it, because you did it! 🎉

**Comment by pkafei** [comment]
Cluster Content Audit: https://docs.google.com/spreadsheets/d/1Y5dASoDwANeahnjjVMDsidOj6qORqb4Agtt_VUQzBuc/edit?usp=sharing
