### ISSUE TITLE
Post-v1 cluster website should provide versioned documentation

### ISSUE THREAD

**Issue by lanzafame** [ipfs/ipfs-cluster-website#88]
For example, cluster.ipfs.io/documentation/v1.0 will point to the v1.0 docs and will exist until v1.0 is deprecated. This means that users won't get confused by following newer versions of the documentation when they are using an older version of Cluster.

**Comment by kishansagathiya** [comment]
This could be done really well if we have all the documentation related markdowns in main repo itself and website just pull info from there. Then you can have not just version-wise docs, but commit-wise docs. There isn't much usefulness in having commitwise docs, but it would make much easier to get version wise docs.

**Comment by pkafei** [comment]
Versioned documentation sounds like a good idea. 

How would the versioning work if it is not based on commits? Will there be a new version every time we document a major change and/or a new feature in Cluster?

**Comment by lanzafame** [comment]
I imagined it would be done on tag, so commit based. The docs don't need to
be in the main repo we just need to tag this repo with the same tag as the
main.

**Comment by pkafei** [comment]
> The docs don't need to be in the main repo we just need to tag this repo with the same tag as the
> main.
> 

Not sure if I understand. So every commit that's merged into master of `ipfs-cluster-website` repo will also update the version of the documentation?

**Comment by lanzafame** [comment]
No, we will have tags that relate to every release of cluster.

**Comment by pkafei** [comment]
I imagine that there will be times where we would update the docs in between cluster releases- how would we update the versioning then? 

We could perhaps borrow from [semantic versioning](https://semver.org/) where our versioning accounts for fixes, updates, and major releases. For instance, if we start at 1.0.0 and then we change the copy of Quickstart for readability purposes, we would go from 1.0.0 to 1.1.0.

**Comment by hsanjuan** [comment]
We will likely have one folder (or git branch) per Cluster tag as to keep an archive of previous docs that can be updated at cleaned without constraints.
