### ISSUE TITLE
Implement toggle feature for left nav

### ISSUE THREAD

**Issue by pkafei** [ipfs/ipfs-cluster-website#91]
Right now it is impossible for the user to toggle from parent to child nav without being redirected to the parent that they click on. 

Goal is to make it so that users can collapse a nav without changing the page that they are on.

**Comment by tapaswenipathak** [comment]
Hi @pkafei: Can I implement the feature?

**Comment by pkafei** [comment]
Hello @tapaswenipathak! Thanks for volunteering to help. I'm on holiday until Wednesday, but when I return I would love to help you get started on some of these tickets.

**Comment by meiqimichelle** [comment]
I believe this is working in the `new-docs-layout` branch. Would appreciate a second pair of 👀 .

**Comment by meiqimichelle** [comment]
This feature has been removed. UX is better without a toggle/accordion. Closing!
