### ISSUE TITLE
Documentation Rewrite

### ISSUE THREAD

**Issue by pkafei** [ipfs/ipfs-cluster-website#93]
Where We Are Now: Documentation sections have been reorganized.

What's Next: The following documentation sections are to be reviewed and rewritten. Below are the different parts of the docs that need to be revised. Each section is linked to the file or folder of the documentation.

Portia and Michelle:

- [ ] [Create introduction to Cluster Documentation](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/_index.md)
- [ ] [IPFS Cluster Overview](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/introduction/overview/introduction.md)
- [ ] [Homeless Content](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/homeless)
- [ ] [API Intro](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/api-overview/api-intro.md)

Adrian, Kishan and Hector:
- [ ] [An introduction to ipfs cluster clt and ipfs cluster service](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/introduction/ipfs-cluster-ctl-and-ipfs-cluster-service.md)
- [ ] [How to Secure Your Cluster (REST, Proxy API, Backup and Security)](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/security/secure-cluster)
- [ ] [Cluster Clients](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/introduction/getting-started/cluster-clients.md)
- [ ] [Adding and Pinning Content](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/introduction/getting-started/pinning.md)
- [ ] [Getting Started](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/introduction/getting-started)
- [ ] [Internals](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/internals)
- [ ] [Guides](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/guides)
- [ ] [Security](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/security)
- [ ] [API Overview](https://github.com/ipfs/ipfs-cluster-website/tree/content/content/documentation/api-overview)

Everyone:
- [ ] [Current Features](https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/introduction/overview/cluster-features.md)

**Comment by hsanjuan** [comment]
@pkafei please verify links above, I think some are not set correctly (Adding and Pinning content etc)

**Comment by pkafei** [comment]
@hsanjuan Thanks, good catch. Fixing now.

**Comment by pkafei** [comment]
Fixed

**Comment by tapaswenipathak** [comment]
Hi folks: Can I PR for the ticket? or is the ticket internal?

**Comment by pkafei** [comment]
Welcome @tapaswenipathak! Did you look at https://github.com/ipfs/docs/issues/226 and https://github.com/ipfs/docs/issues/224. I think they're good starter issues to help you get more familiar with our documentation.

**Comment by tapaswenipathak** [comment]
Thanks @pkafei, the PRs for these tickets are merged. Are the remaining tasks for internal folks? https://github.com/ipfs/ipfs-cluster-website/blob/content/content/documentation/introduction/overview/cluster-features.md is 404ing.

**Comment by meiqimichelle** [comment]
Note: loop back later to make sure [this comment](https://github.com/ipfs/ipfs-cluster-website/pull/96#issuecomment-516768863) is addressed. I'm going to merge the PR it lives in now to help keep branches in sync.

**Comment by meiqimichelle** [comment]
This issue informed a [doc that described the reasoning behind each section](https://docs.google.com/document/d/1051C4XOK6WG0EkD9w2z_gV_vjLzo-cFz8NoXKG5-moo/edit#) so we could get on board with each other's thinking. I will move discussion that starts from that doc to a new issue to keep things easier to follow, as it's a next step after this.

**Comment by hsanjuan** [comment]
Continues in #97
